#ifndef INC_2DGAMEENGINE_CAMERAFOLLOWCOMPONENT_H
#define INC_2DGAMEENGINE_CAMERAFOLLOWCOMPONENT_H

struct CameraFollowComponent {
    CameraFollowComponent() = default;
};

#endif //INC_2DGAMEENGINE_CAMERAFOLLOWCOMPONENT_H